name: "Run once"

on:
  push:

jobs:
  Run:
    name: Test backend - ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
          